//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [Display(Name ="Customer ID :")]
        public int CustomerID { get; set; }

        [Display(Name ="Employee Name :")]
        public string CustomerName { get; set; }

        [Display(Name ="Employee Middle Name :")]
        public string ContactMidName { get; set; }

        [Display(Name ="Employee Phone Number :")]
        public int PhoneNumber { get; set; }

        [Required(ErrorMessage = "Email ID is not in the Valid Format")]
        [Display(Name ="Employee email ID :")]
        [DataType(DataType.EmailAddress)]        
        public string EmailID { get; set; }

        [Required(ErrorMessage = "Password required")]
        [Display(Name ="Password :")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Confirm Password required")]
        [Display(Name ="Confirm Password :")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Error : Confirm password does not match with password")]
        public string ConfirmPassword { get; set; }
    }
}
